on:
  push: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Build Module
        shell: pwsh
        run: Install-Module ModuleBuilder -Force

      - name: Build Module
        shell: pwsh
        run: ./build.ps1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./Output
